- name: "API"
  color: "207de5"
  description: "Issues that handles API changes, not necessarily visible to end users"
- name: "Bad Pull Request"
  color: "eb6420"
  description: "The pull request opened was not accepted, didn't follow the procedures, or was missing information"
- name: "Blocked - External"
  color: "5319e7"
  description: "The issue or pull request is not fixable without a change in a upstream/external library"
- name: "Breaking Change"
  color: "5319e7"
  description: "The issue will introduce backwards incompatible changes"
  aliases: ["BreakingChange"]
- name: "Bug"
  color: "d73a4a"
  description: "Issues where something had happened which was not expected or intended"
  aliases: ["bug"]
- name: "Build"
  color: "0052cc"
  description: "Issues for changes to the build system, without functional changes needed to the project"
  aliases: ["BuildAutomation", "Build Automation"]
- name: "Detail Required"
  color: "9C772F"
  description: "Issues that requires more information about the a problem detected or a feature requested"
- name: "Documentation"
  color: "bfe5bf"
  description: "Issues for changes that only need to change documentation"
  aliases: ["documentation"]
- name: "Duplicate Issue"
  color: "eb6420"
  description: "Issues that are duplicates of other issues"
  aliases: ["duplicate", "duplicates"]
- name: "Enhancement"
  color: "0052cc"
  description: "Issues that enhances existing functionality, or adds new features"
  aliases: ["enhancement"]
- name: "Feature"
  color: "5319e7"
  aliases: ["FeatureParity"]
- name: "Hacktoberfest"
  color: "fb9904"
  description: "Issues opened during hacktoberfest"
- name: "hacktoberfest-accepted"
  color: "1D76DB"
  description: "Pull Requests opened during hacktoberfest, and has been accepted by a team member"
- name: "Invalid / Not Issue / No repro / Not Implementing"
  color: "eb6420"
- name: "invalid"
  color: "e89819"
  description: "This is used to mark Hacktoberfest PR's as invalid"
- name: "NO RELEASE NOTES"
  color: "CCCCCC"
  description: "Should not be included in the release notes - not enhancing or fixing end product"
- name: "No Response / Stale"
  color: "eb6420"
  description: "Used on issues when additional information is requested, and no response has been given"
- name: "Priority_HIGH"
  color: "e11d21"
  description: "Issues that are considered to be a high priority to get fixed"
- name: "Priority_LOW"
  color: "c7def8"
  description: "Issues that are low priority, and will most likely only be fixed by the community"
- name: "Question"
  color: "eb6420"
  description: "Issues opened for asking questions. These should be converted to discussions"
- name: "Requires Upstream Change"
  color: "E10D60"
  description: "Requires changes to a different location once issue is fixed or implemented"
- name: "Security"
  color: "5319e7"
  description: "Issues that are related to security vulnerabilites, or other security related problems"
  aliases: ["security vulnerability"]
- name: "Tests"
  color: "421772"
  description: "Issues related to the tests (NUnit, xUnit, Pester, Etc)"
- name: "Up For Grabs"
  color: "159818"
  description: "Issues that are available by the community to work on"
- name: "Wrong Repository"
  color: "eb6420"
  description: "Issues opened on the wrong repository, and could not be moved"
