group:
  # Common files
  - files:
      - source: .github/workflows/label-sync.yml
        dest: .github/workflows/label-sync.yml
      - source: renovate.json
        dest: renovate.json
        replace: false
    repos:
      WormieCorp/ImageGallery
  - files:
      - source: .github/ISSUE_TEMPLATE/private/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: true
    repos: |
      WormieCorp/ImageGallery
      WormieCorp/GameList
      WormieCorp/PCBS-Utility
