group:
  # Common files
  - files:
      - source: .github/workflows/label-sync.yml
        dest: .github/workflows/label-sync.yml
        replace: false
      - source: renovate.json
        dest: renovate.json
        replace: false
    repos: |
      WormieCorp/CCVARN
      WormieCorp/MediaManager
  - files:
      - source: .github/configs/renovate-semantic.json
        dest: renovate.json
        replace: true
    repes: |
      WormieCorp/CCVARN
      WormieCorp/MediaManager
  - files:
    - source: .github/CCVARN-pre.yml
      dest: CCVARN.yml
    repos: |
      WormieCorp/MediaManager
  - files:
    - source: .github/CCVARN.yml
      dest: CCVARN.yml
    repos: |
      WormieCorp/CCVARN
