group:
  # Common files
  - files:
      - source: .github/workflows/label-sync.yml
        dest: .github/workflows/label-sync.yml
        replace: false
      - source: renovate.json
        dest: renovate.json
        replace: false
    repos: |
      WormieCorp/ImageGallery
      WormieCorp/MyGameList
      WormieCorp/CCVARN
      WormieCorp/MediaManager
  - files:
      - source: .github/ISSUE_TEMPLATE/private/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: true
    repos: |
      WormieCorp/ImageGallery
      WormieCorp/MyGameList
      WormieCorp/PCBS-Utility
  - files:
    - source: .github/CCVARN-pre.yml
      dest: CCVARN.yml
    repos: |
      WormieCorp/ImageGallery
      WormieCorp/MyGameList
      WormieCorp/PCBS-Utility
      WormieCorp/MediaManager
  - files:
    - source: .github/CCVARN.yml
      dest: CCVARN.yml
    repos: |
      WormieCorp/CCVARN
