group:
  # Common files
  - files:
      - source: .github/workflows/label-sync.yml
        dest: .github/workflows/label-sync.yml
    repos:
      WormieCorp/ImageGallery
  - files:
      - source: .github/ISSUE_TEMPLATE/private/
        dest: .github/ISSUE_TEMPLATE/
        deleteOrphaned: true
      - source: .github/ISSUE_TEMPLATE/config.yml
        dest: .github/ISSUE_TEMPLATE/config.yml
    repos: |
      WormieCorp/ImageGallery
      WormieCorp/GameList
      WormieCorp/PCBS-Utility
