name: Feature / Enhancement request
description: Suggest a new idea for this project
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking an interest in this project, and to suggest ideas to improve it!
        Before you start, please make sure that the title have a short concise summary of the idea.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the idea you want to suggest.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your request related to a problem?
      description: If your idea is related to a problem that you want to resolve, then please give a clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: Please add a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please add a clear and concise description of any alternative solutions or features you've considered.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WormieCorp/.github/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or additional log files by clicking this area to highlight it, and then dragging files in.
    validations:
      required: false