name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Disable symlinks
        run: git config --global core.symlink false
      - name: Checkout Repository
        uses: actions/checkout@v2.4.2
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_LABELS: BuildAutomation
