name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.6.0
      - name: Copy needed files
        run: |
          Copy-Item ".github/ISSUE_TEMPLATE/config.yml" ".github/ISSUE_TEMPLATE/private/"
        shell: pwsh
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_LABELS: BuildAutomation
          COMMIT_PREFIX: "chore(sync): "
